version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgresql-codehammer
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - codehammer-network

  config-manager:
    build:
      context: ./config-manager
      dockerfile: Dockerfile
    container_name: config-manager
    restart: always
    env_file:
      - ./config-manager/.env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - '8083:8083'
    depends_on:
      - db
    networks:
      - codehammer-network

  code-processor:
    build:
      context: ./code-processor
      dockerfile: Dockerfile
    container_name: code-processor
    restart: always
    env_file:
      - ./code-processor/.env
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - CONFIG_MANAGER_URL=http://config-manager:8083
      - PROJECT_ID=${PROJECT_ID}
      - TOPIC_ID=${TOPIC_ID}
    ports:
      - '8084:8084'
    depends_on:
      - db
      - config-manager
    networks:
      - codehammer-network

  code-analyzer:
    build:
      context: ./code-analyzer
      dockerfile: Dockerfile
    container_name: code-analyzer
    restart: always
    env_file:
      - ./code-analyzer/.env
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
      - GOOGLE_AI_MODEL_NAME=${GOOGLE_AI_MODEL_NAME}
      - GOOGLE_PROJECT=${GOOGLE_PROJECT}
      - GOOGLE_LOCATION=${GOOGLE_LOCATION}
    ports:
      - '8082:8082'
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS_PATH}:/app/credentials.json
    depends_on:
      - code-processor
    networks:
      - codehammer-network

  portal-web:
    build:
      context: ../portal-web
      dockerfile: Dockerfile
    container_name: portal-web
    restart: always
    environment:
      - REACT_APP_API_URL=http://code-analyzer:8082
    ports:
      - '3000:80'
    depends_on:
      - code-analyzer
      - config-manager
    networks:
      - codehammer-network

networks:
  codehammer-network:
    driver: bridge

volumes:
  postgres_data:
